final practice cont

diff --git a/School_work/cmput_275/a1.posttest/q4/runTests b/School_work/cmput_275/a1.posttest/q4/runTests
--- a/School_work/cmput_275/a1.posttest/q4/runTests
+++ b/School_work/cmput_275/a1.posttest/q4/runTests
@@ -1,34 +1,23 @@
-#!/usr/bin/bash
+#!/bin/bash
 
-command_arg="$1"
-test_set_file="$2"
+cmd_l1="$1"
+testSetFile="$2"
 
+while read stems; do
+        tmp_out=$(mktemp)
+	argument=$(cat "${stems}.args")
+        "${cmd_l1}" $argument < "${stems}.in" > "$tmp_out"
 
+        diff "$tmp_output" "${stems}.out" > /dev/null
 
-while read -r stem; do 
-    # Run the command and capture its output
-    x=$(${command_arg} $(cat ${stem}.args) <  "${stem}.in")
-	
-
-    # Create a temporary file
-    temp_file=$(mktemp)
-
-    # Write the command's output to the temporary file
-    echo "$x" > "$temp_file"
-
-    # Compare the temporary file with the expected output
-    if diff "$temp_file" "${stem}.out" > /dev/null; then
-        echo "Test ${stem} passed"
-    else
-        echo "Test ${stem} failed"
-        echo "Expected output:"
-        cat "${stem}.out"
-        echo "Actual output:"
-        cat "$temp_file"
-    fi
-
-    # Remove the temporary file
-    rm "$temp_file"
-done < "$test_set_file"
-
-
+        if [ $? -eq 0 ]; then
+                echo "Test ${stems} passed"
+        else
+                echo "Test ${stems} failed"
+                echo "Expected output:"
+                cat "${stems}.out"
+                echo "Actual output:"
+                cat "$tmp_out"
+        fi
+        rm "$tmp_out"
+done < "$testSetFile"
